"""add segmentation columns to astronomical_objects

Revision ID: 2abf67c31898
Revises: 8b7ed9ebe193
Create Date: 2026-02-23 00:40:01.062907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2abf67c31898'
down_revision: Union[str, Sequence[str], None] = '8b7ed9ebe193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('astronomical_objects', sa.Column('segmentation_mask_rle', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('astronomical_objects', sa.Column('cutout_s3_prefix', sa.String(), nullable=True))
    op.add_column('astronomical_objects', sa.Column('bounding_box_pixels', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('astronomical_objects', sa.Column('detection_signal_to_noise_ratio', sa.Float(), nullable=True))
    detection_confidence_tier_enum = sa.Enum('high', 'medium', 'low', name='detection_confidence_tier_enum')
    detection_confidence_tier_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('astronomical_objects', sa.Column('detection_confidence_tier', detection_confidence_tier_enum, nullable=True))
    op.add_column('astronomical_objects', sa.Column('detection_scale_level', sa.String(), nullable=True))
    op.add_column('astronomical_objects', sa.Column('is_edge_detection', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('astronomical_objects', sa.Column('pixel_centroid_x', sa.Float(), nullable=True))
    op.add_column('astronomical_objects', sa.Column('pixel_centroid_y', sa.Float(), nullable=True))
    op.add_column('astronomical_objects', sa.Column('segmentation_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('astronomical_objects', 'segmentation_method')
    op.drop_column('astronomical_objects', 'pixel_centroid_y')
    op.drop_column('astronomical_objects', 'pixel_centroid_x')
    op.drop_column('astronomical_objects', 'is_edge_detection')
    op.drop_column('astronomical_objects', 'detection_scale_level')
    op.drop_column('astronomical_objects', 'detection_confidence_tier')
    sa.Enum('high', 'medium', 'low', name='detection_confidence_tier_enum').drop(op.get_bind(), checkfirst=True)
    op.drop_column('astronomical_objects', 'detection_signal_to_noise_ratio')
    op.drop_column('astronomical_objects', 'bounding_box_pixels')
    op.drop_column('astronomical_objects', 'cutout_s3_prefix')
    op.drop_column('astronomical_objects', 'segmentation_mask_rle')
    # ### end Alembic commands ###
