"""initial schema with observations, processing steps, objects, catalog matches

Revision ID: 8b7ed9ebe193
Revises: 
Create Date: 2026-02-21 21:58:42.968070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b7ed9ebe193'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observations',
    sa.Column('observation_uuid', sa.UUID(), nullable=False),
    sa.Column('archive_observation_id', sa.String(), nullable=False),
    sa.Column('archive_program_id', sa.String(), nullable=True),
    sa.Column('telescope_name', sa.String(), nullable=False),
    sa.Column('instrument_name', sa.String(), nullable=False),
    sa.Column('spectral_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_exposure_seconds', sa.Float(), nullable=True),
    sa.Column('pointing_ra_degrees', sa.Float(), nullable=True),
    sa.Column('pointing_dec_degrees', sa.Float(), nullable=True),
    sa.Column('pipeline_status', sa.Enum('pending', 'downloading', 'processing', 'completed', 'failed', name='pipeline_status_enum'), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('observation_uuid'),
    sa.UniqueConstraint('archive_observation_id')
    )
    op.create_table('astronomical_objects',
    sa.Column('object_uuid', sa.UUID(), nullable=False),
    sa.Column('source_observation_uuid', sa.UUID(), nullable=False),
    sa.Column('sky_coordinate_ra_degrees', sa.Float(), nullable=False),
    sa.Column('sky_coordinate_dec_degrees', sa.Float(), nullable=False),
    sa.Column('classified_object_type', sa.String(), nullable=True),
    sa.Column('classification_source_catalog', sa.String(), nullable=True),
    sa.Column('classification_confidence_score', sa.Float(), nullable=True),
    sa.Column('physical_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_anomaly_flagged', sa.Boolean(), nullable=False),
    sa.Column('detected_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_observation_uuid'], ['observations.observation_uuid'], ),
    sa.PrimaryKeyConstraint('object_uuid')
    )
    op.create_table('processing_steps',
    sa.Column('step_uuid', sa.UUID(), nullable=False),
    sa.Column('observation_uuid', sa.UUID(), nullable=False),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('step_status', sa.Enum('pending', 'running', 'completed', 'failed', 'skipped', name='step_status_enum'), nullable=False),
    sa.Column('step_started_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('step_completed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('error_message_text', sa.Text(), nullable=True),
    sa.Column('step_output_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['observation_uuid'], ['observations.observation_uuid'], ),
    sa.PrimaryKeyConstraint('step_uuid')
    )
    op.create_table('catalog_cross_matches',
    sa.Column('match_uuid', sa.UUID(), nullable=False),
    sa.Column('object_uuid', sa.UUID(), nullable=False),
    sa.Column('catalog_name', sa.String(), nullable=False),
    sa.Column('catalog_source_id', sa.String(), nullable=False),
    sa.Column('angular_separation_arcseconds', sa.Float(), nullable=False),
    sa.Column('match_probability_score', sa.Float(), nullable=True),
    sa.Column('raw_catalog_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['object_uuid'], ['astronomical_objects.object_uuid'], ),
    sa.PrimaryKeyConstraint('match_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_cross_matches')
    op.drop_table('processing_steps')
    op.drop_table('astronomical_objects')
    op.drop_table('observations')
    # ### end Alembic commands ###
